version: '3'

services:
  db:
    container_name: app_backend_db
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
    - ./:/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
    - api_net
  backend:
    container_name: app_backend
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    depends_on:
      - db
    # caso nao queira utilizar rodar o projeto com npm start, 
    # comente a linha abaixo e descomente a linha 29
    # command: sh -c "npm install && npm start"
    command: sh -c "npm install && npm run dev"
    environment:
      MYSQLHOST: db
      MYSQLUSER: "root"
      MYSQLPASSWORD: 123456
    networks:
    - api_net
networks:
  api_net:
    driver: bridge