version: '3'

services:
  db:
    container_name: app_backend_db
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
    - ./:/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
    - api_net
  backend:
    container_name: app_backend
    build: .
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    ports:
      - "3001:3001"
    volumes:
      # Monta o diretório atual, com todos os dados do projeto, 
      # dentro do diretório /app
      - ./:/app
    depends_on:
      - db
    environment:
      MYSQLHOST: db
      MYSQLUSER: "root"
      MYSQLPASSWORD: 123456
    networks:
    - api_net
# Lista de redes que os containeres irão utilizar
# Cria rede com nome `api_net`
# Define o `driver` como `bridge`, que é o driver padrão do docker
networks:
  api_net:
    driver: bridge